[package]
name = "vad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.10.1"
dasp = {version = "*", features = ["all"]}
symphonia = { version = "0.5.1", features = ["isomp4", "aac"] }