import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Button from "@mui/material/Button";

import { useEffect, useState } from "react";

export default function Home() {
  const [outValue, setOutValue] = useState("");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Autouato</a>, {outValue}
        </h1>
        <Button variant="contained">Hello World</Button>
        <Button variant="contained">Hello World</Button>
      </main>

      <footer className={styles.footer}>
        <a href="miantu.net" target="_blank" rel="noopener noreferrer">
          Powered by GoooIce
        </a>
      </footer>
    </div>
  );
}
